snapcraft.yaml
name: newyearsbot
version: "1.3"
summary: NYE irc party bot
description: Prints new years in each timezone as they happen
confinement: strict

apps:
  newyearsbot:
    command: newyearsbot
  newyearsbot-gui:
    command: newyearsbot-gui

parts:
  newyearsbot:
    plugin: make
    source: ../